name: luxe_desires
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  get: ^4.6.5
  google_fonts: ^5.1.0
  flutter_bounce: ^1.1.0
  flutter_svg: ^2.0.7
  extended_image: ^8.0.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_spinkit: ^5.2.0
  lottie: ^2.5.0
  url_launcher: ^6.1.12
  get_storage: ^2.1.1
  font_awesome_flutter: ^10.5.0
  chewie: ^1.7.0
  video_player: ^2.7.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/gif/
